### PR TITLE
Added a welcome bot

### PR DESCRIPTION
**Pull request by m-code12**
Fixes: #7 

### What is the change?
Added a GitHub action to auto assign mentors for every pr.

### How was it tested?
I have tested the GitHub action in my personal repository. It automatically adds me as a reviewer on every pr created. Here is a link to the repo:
https://github.com/m-code12/Test_repo

What is the change?
Created config.yml file for the welcome bot to help first-time contributors. To activate the app you need to go to https://github.com/apps/welcome and click on install and give the app the required permissions (Pull requests: Read & Write
Issues: Read & Write).

### CODE REVIEW

**Comment by m-code12** [comment]
@YashKumarVerma Please review and merge this pr. Also, do we have a slack or discord channel for this project? We could add that in the welcome bot.

**Comment by m-code12** [comment]
@YashKumarVerma Do we have a slack or discord channel for this project? We could add that in the welcome bot.

**Comment by YashKumarVerma** [comment]
Thanks @m-code12 , i've created this discord channel.https://discord.gg/4x2uuWqhKU

**Comment by YashKumarVerma** [comment]
also, can you share the docs for the bot so I can refer.

**Comment by m-code12** [comment]
> also, can you share the docs for the bot so I can refer.

Yes, https://github.com/apps/welcome

**Review by YashKumarVerma — APPROVED** [review]

**Comment by m-code12** [comment]
@YashKumarVerma This issue was for hard/100 points, right?
Also, one more thing I have to include the discord link in the bot, should I raise another pr ?

**Comment by YashKumarVerma** [comment]
sure, please add the link in the bot in a subsequent pr. you can open the issue for it.

i had changed the points to 50 as it was not a very difficult task.

**Comment by m-code12** [comment]
> sure, please add the link in the bot in a subsequent pr. you can open the issue for it.
> 
> i had changed the points to 50 as it was not a very difficult task.

Okay I am opening a new issue for it.

**Pull request merged**
